In [5]:
import numpy as np
#import matplotlib.pyplot as plt

In [14]:
#chess board
a = np.arange(1,37,1).reshape(6,6)
b = [i%2 for i in a]
b


[array([0, 1, 0, 1, 0, 1], dtype=int32),
 array([0, 1, 0, 1, 0, 1], dtype=int32),
 array([0, 1, 0, 1, 0, 1], dtype=int32),
 array([0, 1, 0, 1, 0, 1], dtype=int32),
 array([0, 1, 0, 1, 0, 1], dtype=int32),
 array([0, 1, 0, 1, 0, 1], dtype=int32)]